"""
Using ChatGPT to normalise list of majors, ensuring consistency

Prompt: 
Consider the following list of majors offered by the National University of Singapore (NUS):

<insert list here>

Some of these majors are actually the same. For example, "dsa" is an abbreviation of "data science and analytics", which is also the same as "data science & analytics" and “Data Science and Analytics”. With reference to information that you can find regarding the names and abbreviations of NUS majors, please carry out a one-to-one mapping of this list of majors, ensuring that the same majors are mapped to the same output (all in lowercase). Do the mapping element-wise, returning a Python list of strings. Since the mapping is one-to-one, the length of the list should not change.
"""

cleaned_majors = [
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'life sciences',
    'data science and analytics',
    'life sciences',
    'nursing',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'social work',
    'business administration',
    'data science and analytics',
    'data science and analytics',
    'nursing',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'computer science',
    'life sciences',
    'dentistry',
    'geography',
    'geography',
    'political science',
    'psychology',
    'computer science',
    'business',
    'data science and analytics',
    'environmental studies',
    'data science and analytics',
    'dentistry',
    'dentistry',
    'data science and analytics',
    'data science and analytics',
    'mathematics',
    'data science and analytics',
    'data science and analytics',
    'law',
    'data science and analytics',
    'data science and analytics',
    'computer science',
    'chemistry',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'sociology',
    'data science and analytics',
    'computer science',
    'data science and analytics',
    'data science and analytics',
    'computer science',
    'computer science',
    'computer science',
    'economics',
    'history',
    'data science and analytics',
    'data science and analytics',
    'mechanical engineering',
    'data science and analytics',
    'data science and analytics',
    'materials science and engineering',
    'political science',
    'malay studies',
    'global studies',
    'anthropology',
    'accountancy',
    'life sciences',
    'geography',
    'pharmaceutical science',
    'economics',
    'nursing',
    'history',
    'life sciences',
    'engineering',
    'biomedical engineering',
    'quantitative finance',
    'data science and analytics',
    'environmental studies',
    'life sciences',
    'psychology',
    'data science and analytics',
    'statistics',
    'engineering - material science and engineering',
    'materials science and engineering',
    'data science and analytics',
    'data science and analytics',
    'life sciences',
    'data science n psychology',
    'data science and analytics',
    'data science and analytics',
    'data science and analytics',
    'economics',
    'economics',
    'sociology',
    'data science and analytics',
    'sociology',
    'data science and analytics',
    'anthropology'
]