#Test case for cleaned data
# Test case for clean
# cleaned_majors = clean_major(test.fields_of_study)

fields_of_study = [
    "DSA", "DSA", "DSA", "DSA", "Data Science", "DSA", "data science", "Environmental Studies",
    "Computer Science", "DSA", "life sciences", "Business", "Dentistry", "Dentistry", "DSA",
    "Data Science and Analytics", "DSA", "Life science", "nursing", "DSA", "Business Administration",
    "social work", "Data Science and Analytics", "Nursing", "Data Science and Analytics",
    "Data Science and Analytics", "Data Science and Analytics", "Data Science and Analytics",
    "Data Science and Analytics", "CS", "Life Sciences", "Faculty of Dentistry", "Geography",
    "Geography", "Political Sciences", "Psychology", "Computer Science", "DSA", "DSA", "DSA",
    "Mathematics", "Chemistry", "Law", "data science & analytics", "cs", "Dsa", "DSA", "DSA",
    "dsa", "dsa", "sociology", "DSA", "DSA", "DSA", "CS", "Computer Science", "Computer Science",
    "Economics", "DSA", "DSA", "DSA", "Data Science and Analytics", "History", "DSA", "DSA",
    "Mechanical Engineering", "DSA", "Materials Science and Engineering", "political science",
    "malay studies", "global studies", "Anthropology", "Accountancy", "Life Sci", "geography",
    "pharmaceutical science", "Economics", "DSA", "life science", "DSA", "Nursing", "History",
    "life sciences", "Engineering", "Biomedical Engineering", "Quantitative Finance", "EVE", 
    "Psych", "DSA", "Statistics", "Engineering - Material Science and Engineering",
    "Materials Science and Engineering", "Environmental Science", "DSA", "DSA", "Life Science",
    "data science n psychology", "Data Science & Analytics", "DSA", "sociology", "dsa",
    "Anthropology", "Environmental Science", "DSA", "Economics", "Economics", "sociology", 
    "dsa", "Data science and analytics", "Data Science and Analytics", "Dsa", "PPE-XDP",
    "Business Analytics", "Chemistry", "Mathematics", "Psychology", "Life science", "DSA",
    "chem", "Architecture", "Life Science", "food science and technology", "mathematics", 
    "Law", "Dentistry", "Dentistry", "Nursing", "FST", "DSA", "DSA", "Ise", "Anthropology", 
    "Life Science", "food science and technology", "food science and technology", "mathematics", 
    "Law", "Dentistry", "Nursing", "Environmental Science", "DSA", "Mathematics", "Econs",
    "Anthropology", "Life Science", "food science and technology", "mathematics", "mathematics", 
    "Law", "Political Sciences", "Dentistry", "Nursing", "DSA", "sociology", "social work", 
    "Anthropology", "Life Science", "food science and technology", "mathematics", "Psychology", 
    "Political Sciences", "Political Sciences", "Dentistry", "cs", "DSA", "psych", "FST", 
    "DSA", "social work", "DSA", "Anthropology", "Life Science", "food science and technology", 
    "mathematics", "Malay Studies", "Global Studies", "Political Sciences", "Nursing", 
    "data science and analytics!", "Geography", "DSA", "DSA", "Anthropology", 
    "material science & engineering", "statistics", "life sciences", "Malay Studies", 
    "Global Studies", "Psychology", "Law", "Political Sciences", "Nursing", "Environmental Science", 
    "Anthropology", "DSA", "Malay Studies", "Global Studies", "Global Studies", 
    "Political Sciences", "Chemistry", "Malay Studies", "Global Studies", "Psychology", 
    "Malay Studies", "Global Studies", "Psychology", "Psychology", "Law", "Nursing", 
    "Malay Studies", "Psychology", "Law", "Dentistry", "material science & engineering", 
    "statistics", "life sciences", "economics", "economics", "economics", "economics", 
    "economics", "economics", "sociology", "sociology", "sociology", "sociology", 
    "Environmental Science", "sociology", "Environmental Science", "sociology", "Chemistry", 
    "Computer Science", "Computer Science", "Chemistry", "Computer Science", "Chemistry", 
    "Chemistry", "DSA", "adsa", "Computer Science", "Computer Science", "Computer Science", 
    "Social Work", "Social Work", "Social Work", "Social Work", "Social Work", "Social Work", 
    "Chemistry", "Chemistry", "History", "statistics", "History", "History", 
    "material science & engineering", "life sciences", "History", "material science & engineering", 
    "History", "statistics", "life sciences", "History", "material science & engineering", 
    "statistics", "life sciences", "material science & engineering", "statistics", 
    "life sciences", "architecture", "Architecture", "architecture", "architecture", 
    "architecture", "architecture", "biomedical engineering", "biomedical engineering", 
    "biomedical engineering", "biomedical engineering", "biomedical engineering", 
    "biomedical engineering", "biomedical engineering", "biomedical engineering", "bza", 
    "bza", "bza", "bza", "bza", "bza", "politics, philosophy, economics", 
    "politics, philosophy, economics", "politics, philosophy, economics", 
    "politics, philosophy, economics", "politics, philosophy, economics", 
    "politics, philosophy, economics", "Mechanical engineering", "Mechanical engineering", 
    "Mechanical engineering", "Mechanical Engineering", "Mechanical Engineering", 
    "Mechanical Engineering", "Geography", "Geography", "Geography", "Geography", 
    "Geography", "Quantitative finance", "Quantitative Finance"
]
